### PR TITLE
swap out backbone-events-standalone for ampersand-events

### PR DESCRIPTION
**Pull request by lukekarrys**

### CODE REVIEW

**Comment by wraithgar** [comment]
+1

**Comment by HenrikJoreteg** [comment]
:shipit:

**Comment by wraithgar** [comment]
Gonna hold off on a release to see if I can find time to knock out https://github.com/AmpersandJS/ampersand-subcollection/issues/43 today

**Comment by wraithgar** [comment]
released as `v2.0.2`

**Pull request merged**
