### PR TITLE
replace underscore with lodash modules

### PR DESCRIPTION
**Pull request by klaemo**
I really want to get rid of the underscore dependency in ampersand :D
The next step would be to replace the underscore-mixin with a lodash one.

### CODE REVIEW

**Comment by klaemo** [comment]
I force pushed an amend commit, with lodash as a devDep.

**Comment by wraithgar** [comment]
The refactors both use amp currently and need to be switched to lodash, this module is going to be changed to use the refactors https://github.com/AmpersandJS/ampersand-subcollection/issues/43

**Comment by wraithgar** [comment]
Merging #47 since it doesn't have conflicts.

**Comment by wraithgar** [comment]
released as `v2.0.2`

**Pull request closed without merging**
