### PR TITLE
bubble change event if model was initially a member | closes #39

### LINKED ISSUE #39: When do subCollections update in relation to `change` events?
Moving this here from AmpersandJS/ampersand-state#130 /cc @cmalven

---

I'm running into an issue where the order of operations is not what I expect, and I'm not sure how it's supposed to work or how to get around it.

**Issue:** In the following, I would prefer the `change:selected` callback for `models/ingredient.coffee` to always take place after the collection's subCollection has been updated. It isn't. The first time an ingredient's `selected` property is updated, the callback's `console.log` will output `0` (when it should output `1`). When another ingredient becomes `selected`, the output will be `1` (as opposed to `2`) If one of those ingredients becomes un-`selected`, the output will be `2`.

So, it seems that the subCollection isn't being updated until after the `change` event, which makes things difficult.

Assuming this is the desired behavior, what is a good way to work around this and still give each `ingredient` model a way of knowing which of its sibling models is `selected`?

Collection: `models/ingredients.coffee`

```
module.exports = Collection.extend

  initialize: ->
    @selectedIngredients = new SubCollection @,
      where:
        selected: true
  
  model: Ingredient
```

Model: `models/ingredient.coffee`

```
module.exports = State.extend
  
  initialize: ->
    @listenTo @collection, 'change:selected', (evt) =>

      console.log(@collection.selectedIngredients.length)
…
```

View: `views/ingredient.coffee`

```
module.exports = View.extend

  template: ingredientTemplate

  events:
    'click': 'handleClick'

  bindings:

    'model.selected':
      type: 'booleanClass'
      hook: 'title'
      name: 'is-selected'

  render: ->
    @renderWithTemplate()

  handleClick: ->
    @model.toggle('selected')
```

### PR DESCRIPTION
**Pull request by aaronmccall**

### CODE REVIEW

**Comment by HenrikJoreteg** [comment]
did you see my comment here? https://github.com/AmpersandJS/ampersand-subcollection/issues/39#issuecomment-70936903

**Comment by aaronmccall** [comment]
Yes, I have. I think the current behaviour is still a bug because, at the time that the event fired, the model was a member of the subcollection, so it should bubble.

**Comment by HenrikJoreteg** [comment]
so, what I'm asking is should we also bubble change events for changes to things in the base collection that cause them to become part of the sub collection? To me, the distinction is rather ambiguous. 

I'd almost wonder if we should instead make it so that we don't bubble change events for things that affect a model's presence in the subcollection.

**Comment by aaronmccall** [comment]
Ah, I see now. Good question. I think we may want to handle `change:*` events separately from other events because they need more nuanced handling in terms of logic.

I'd say that we don't bubble events that cause models to become members because they weren't a member until after the change event fired, whereas the reverse should bubble.

My thought process:

Suppose I have an external event handler that is listening to events on one collection (A) and adding or removing them on another (B) based on some filters. When an event is received that makes a model from A eligible to be a member of B it is added, but the event only bubbles on A because B wasn't aware of it when the event occurred. On the other hand, if our external handler intercepts a change on a model that causes the model to be removed from B the event would still bubble on B because, at the time of the event, the model _was_ a member of B.

```javascript
function handler(A, B, filter) {
  A.on('all', function (event, model) {
    if (model.isState && model.collection === A) {
      var isMember = B.get(model);
      var passes = filter(model);
      if (passes && !isMember) {
        // B will never bubble change events that got us here
        B.add(model);
      } else if (!passes && isMember) {
        // B will always bubble change events that got us here
        B.remove(model);
      }
    }
  });
}
```

**Comment by wraithgar** [comment]
@aaronmccall can you revisit this here https://github.com/AmpersandJS/ampersand-filtered-subcollection instead?

**Pull request closed without merging**
