### PR TITLE
replace underscore-mixin with lodash-mixin

### PR DESCRIPTION
**Pull request by flipside**

### CODE REVIEW

**Comment by wraithgar** [comment]
Looks good, but please note that this module is deprecated and you may want to consider using paginated/filtered subcollection instead.

**Comment by flipside** [comment]
good to know, maybe add that in the readme?

**Comment by lukekarrys** [comment]
I'm +1 on this prior to #43. Makes sense to do one more patch release with lodash in there I think.

**Comment by wraithgar** [comment]
Gonna just merge this and then deprecate.  Thanks @flipside!!!!

**Comment by wraithgar** [comment]
Released as `v2.0.3`

**Pull request merged**
