### PR TITLE
sort as described in docs | fixes #33

### LINKED ISSUE #33: comparator behaviour inconsistent with &-collection & own docs
I've just chatted a bit with a couple of devs in the gitter channel. They've run into a problem with the comparator not working as expected when it's a function. It doesn't follow the collection comparator spec or the docs as written.

If I rewire sorting to use the `_sort` method that is in #32, this issue will be resolved.

cc: @bernharduw and @Twinski

### PR DESCRIPTION
**Pull request by aaronmccall**
ref #33

### CODE REVIEW

**Comment by latentflip** [comment]
This is basically the code from ampersand-collection so +1 since that sorting seems to be working fine.

Couple of issues, though maybe should be logged over there:

1. Could/should this be a module? Seems a shame to have the code in both places but slightly different
2. These lines https://github.com/AmpersandJS/ampersand-collection/blob/master/ampersand-collection.js#L220-L226 assume that both left and right are the same type of thing. It's conceivable that left could be a model and right could be an object, in which case this would explode as it would try and call `get` on right. Not a huge deal, but, potential issue.

**Comment by latentflip** [comment]
I changed my mind a little, there's also this: https://github.com/AmpersandJS/object-sort/blob/master/README.md maybe we should be using that in both places?

**Comment by aaronmccall** [comment]
@latentflip, it seems like `object-sort` behaves the same for all of the cases that &-collection sorting currently handles except that it never uses the `.get('prop')` approach. The only case where that should be an issue is where you're putting Backbone models into an &-collection, though.

**Comment by aaronmccall** [comment]
I'm all for the switch though. It's not hard to convert Backbone models to &-model/state and probably should be done together (collection and its model/state).

**Comment by kamilogorek** [comment]
@aaronmccall @latentflip How about transforming it into `amp-sort` module first?

**Comment by aaronmccall** [comment]
@kamilogorek, maybe we merge this then replace later? As it stands now, sorting is broken.

**Comment by kamilogorek** [comment]
@aaronmccall I'm totally fine with that, as we can always patch it's internals without changing it's functionality, therefore I'd say +1

**Comment by aaronmccall** [comment]
@latentflip, what do you say? Merge and also add an enhancement issue to update to use amp-sort/object-sort?

**Comment by latentflip** [comment]
Sure thing. Works for me.

**Pull request merged**
