### PR TITLE
add change log for 2.0.0

### PR DESCRIPTION
**Pull request by aaronmccall**

### CODE REVIEW

**Comment by fyockm** [comment]
I would also include something about exposing the `reset()` convenience method. 

might just be me, but I think it would be nice to specifically highlight what caused the major bump (if anything).

**Comment by kamilogorek** [comment]
@fyockm yeah, I guess it'd be nice addition. @aaronmccall if you could add it, +1 from me.

**Comment by aaronmccall** [comment]
@fyockm, no one thing led to the version bump, rather the extent of the changes. I've broken out `reset()` to its own changelog bullet. /cc @kamilogorek

**Comment by fyockm** [comment]
@aaronmccall LGTM now. I like how you reordered some of the bullets.

**Pull request merged**
